### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by jatin69** [jatin69/du-result-fetcher#1]
The code right now has a lot of moving parts and unnecessary code blocks.
Refactor the DU-UG-2018 folders. 
Make constants variables on top of the file that can be simply used in the code.

## Example -
Instead of 
```python
r = requests('http://blah')
```
Use 
```python
studentURL = 'http://blah'
r = requests(studentURL)
```

**Comment by rob-deans** [comment]
Still need help with the refactoring?

**Comment by jatin69** [comment]
Hey @rob-deans , the commit above did most of the work. It won't be wise to spend more time on it. Thanks though.
