### ISSUE TITLE
Design a configuration file

### ISSUE THREAD

**Issue by jatin69** [jatin69/du-result-fetcher#2]
To avoid a lot of constants in a lot of old and new scripts, 
Design an appropriate config file and update scripts accordingly.

## Example

config.yml
```yaml
MCA = {
    studentURL = 'http://blah' 
}
```
scripts.py
```python
import config
r = requests(config.MCA.studentURL)
```

**Comment by destag** [comment]
Can I take this one?

**Comment by jatin69** [comment]
Sure. Go ahead. Let me know if you need anything else. I'll suggest you start with one script first, get it reviewed and then move on to others.
